/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Captain Tok - AI News & Investing Blog API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Book,
  BookInput,
  CheckoutSession,
  CheckoutSessionInput,
  ContactInput,
  ContactSubmission,
  Digest,
  DigestInput,
  DigestUpdate,
  DownloadFileParams,
  DownloadLink,
  GetDownloadLinkParams,
  HealthStatus,
  ListDigestsParams,
  ListPostsParams,
  NewsletterInput,
  NewsletterSubscriber,
  Post,
  PostInput,
  PostUpdate,
  StripeKey
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListPostsUrl = (params?: ListPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/posts?${stringifiedParams}` : `/api/posts`
}

/**
 * @summary List all blog posts
 */
export const listPosts = async (params?: ListPostsParams, options?: RequestInit): Promise<Post[]> => {

  return customFetch<Post[]>(getListPostsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPostsQueryKey = (params?: ListPostsParams,) => {
    return [
    `/api/posts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPostsQueryOptions = <TData = Awaited<ReturnType<typeof listPosts>>, TError = ErrorType<unknown>>(params?: ListPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPosts>>> = ({ signal }) => listPosts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPostsQueryResult = NonNullable<Awaited<ReturnType<typeof listPosts>>>
export type ListPostsQueryError = ErrorType<unknown>


/**
 * @summary List all blog posts
 */

export function useListPosts<TData = Awaited<ReturnType<typeof listPosts>>, TError = ErrorType<unknown>>(
 params?: ListPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPostsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreatePostUrl = () => {




  return `/api/posts`
}

/**
 * @summary Create a new blog post
 */
export const createPost = async (postInput: PostInput, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getCreatePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postInput,)
  }
);}




export const getCreatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<PostInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<PostInput>}, TContext> => {

const mutationKey = ['createPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPost>>, {data: BodyType<PostInput>}> = (props) => {
          const {data} = props ?? {};

          return  createPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createPost>>>
    export type CreatePostMutationBody = BodyType<PostInput>
    export type CreatePostMutationError = ErrorType<unknown>

    /**
 * @summary Create a new blog post
 */
export const useCreatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<PostInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPost>>,
        TError,
        {data: BodyType<PostInput>},
        TContext
      > => {
      return useMutation(getCreatePostMutationOptions(options));
    }

export const getGetPostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

/**
 * @summary Get a single blog post
 */
export const getPost = async (id: number, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getGetPostUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPostQueryKey = (id: number,) => {
    return [
    `/api/posts/${id}`
    ] as const;
    }


export const getGetPostQueryOptions = <TData = Awaited<ReturnType<typeof getPost>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPost>>> = ({ signal }) => getPost(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPostQueryResult = NonNullable<Awaited<ReturnType<typeof getPost>>>
export type GetPostQueryError = ErrorType<void>


/**
 * @summary Get a single blog post
 */

export function useGetPost<TData = Awaited<ReturnType<typeof getPost>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPostQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdatePostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

/**
 * @summary Update a blog post
 */
export const updatePost = async (id: number,
    postUpdate: PostUpdate, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getUpdatePostUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postUpdate,)
  }
);}




export const getUpdatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{id: number;data: BodyType<PostUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{id: number;data: BodyType<PostUpdate>}, TContext> => {

const mutationKey = ['updatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePost>>, {id: number;data: BodyType<PostUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePost(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePost>>>
    export type UpdatePostMutationBody = BodyType<PostUpdate>
    export type UpdatePostMutationError = ErrorType<unknown>

    /**
 * @summary Update a blog post
 */
export const useUpdatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{id: number;data: BodyType<PostUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updatePost>>,
        TError,
        {id: number;data: BodyType<PostUpdate>},
        TContext
      > => {
      return useMutation(getUpdatePostMutationOptions(options));
    }

export const getDeletePostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

/**
 * @summary Delete a blog post
 */
export const deletePost = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeletePostUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeletePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePost>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePost(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePost>>>

    export type DeletePostMutationError = ErrorType<unknown>

    /**
 * @summary Delete a blog post
 */
export const useDeletePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePost>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePostMutationOptions(options));
    }

export const getGetRecentPostsUrl = () => {




  return `/api/posts/recent`
}

/**
 * @summary Get 3 most recent posts for homepage
 */
export const getRecentPosts = async ( options?: RequestInit): Promise<Post[]> => {

  return customFetch<Post[]>(getGetRecentPostsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRecentPostsQueryKey = () => {
    return [
    `/api/posts/recent`
    ] as const;
    }


export const getGetRecentPostsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentPosts>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentPostsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentPosts>>> = ({ signal }) => getRecentPosts({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentPosts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecentPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentPosts>>>
export type GetRecentPostsQueryError = ErrorType<unknown>


/**
 * @summary Get 3 most recent posts for homepage
 */

export function useGetRecentPosts<TData = Awaited<ReturnType<typeof getRecentPosts>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecentPostsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListBooksUrl = () => {




  return `/api/books`
}

/**
 * @summary List all books
 */
export const listBooks = async ( options?: RequestInit): Promise<Book[]> => {

  return customFetch<Book[]>(getListBooksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBooksQueryKey = () => {
    return [
    `/api/books`
    ] as const;
    }


export const getListBooksQueryOptions = <TData = Awaited<ReturnType<typeof listBooks>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBooks>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBooksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBooks>>> = ({ signal }) => listBooks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBooks>>, TError, TData> & { queryKey: QueryKey }
}

export type ListBooksQueryResult = NonNullable<Awaited<ReturnType<typeof listBooks>>>
export type ListBooksQueryError = ErrorType<unknown>


/**
 * @summary List all books
 */

export function useListBooks<TData = Awaited<ReturnType<typeof listBooks>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBooks>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListBooksQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateBookUrl = () => {




  return `/api/books`
}

/**
 * @summary Create a new book
 */
export const createBook = async (bookInput: BookInput, options?: RequestInit): Promise<Book> => {

  return customFetch<Book>(getCreateBookUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookInput,)
  }
);}




export const getCreateBookMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBook>>, TError,{data: BodyType<BookInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createBook>>, TError,{data: BodyType<BookInput>}, TContext> => {

const mutationKey = ['createBook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBook>>, {data: BodyType<BookInput>}> = (props) => {
          const {data} = props ?? {};

          return  createBook(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateBookMutationResult = NonNullable<Awaited<ReturnType<typeof createBook>>>
    export type CreateBookMutationBody = BodyType<BookInput>
    export type CreateBookMutationError = ErrorType<unknown>

    /**
 * @summary Create a new book
 */
export const useCreateBook = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBook>>, TError,{data: BodyType<BookInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createBook>>,
        TError,
        {data: BodyType<BookInput>},
        TContext
      > => {
      return useMutation(getCreateBookMutationOptions(options));
    }

export const getGetBookUrl = (id: number,) => {




  return `/api/books/${id}`
}

/**
 * @summary Get a single book
 */
export const getBook = async (id: number, options?: RequestInit): Promise<Book> => {

  return customFetch<Book>(getGetBookUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBookQueryKey = (id: number,) => {
    return [
    `/api/books/${id}`
    ] as const;
    }


export const getGetBookQueryOptions = <TData = Awaited<ReturnType<typeof getBook>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBook>>> = ({ signal }) => getBook(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBookQueryResult = NonNullable<Awaited<ReturnType<typeof getBook>>>
export type GetBookQueryError = ErrorType<void>


/**
 * @summary Get a single book
 */

export function useGetBook<TData = Awaited<ReturnType<typeof getBook>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBookQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListDigestsUrl = (params?: ListDigestsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reader?${stringifiedParams}` : `/api/reader`
}

/**
 * @summary List all children's book digests
 */
export const listDigests = async (params?: ListDigestsParams, options?: RequestInit): Promise<Digest[]> => {

  return customFetch<Digest[]>(getListDigestsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDigestsQueryKey = (params?: ListDigestsParams,) => {
    return [
    `/api/reader`, ...(params ? [params] : [])
    ] as const;
    }


export const getListDigestsQueryOptions = <TData = Awaited<ReturnType<typeof listDigests>>, TError = ErrorType<unknown>>(params?: ListDigestsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDigests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDigestsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDigests>>> = ({ signal }) => listDigests(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDigests>>, TError, TData> & { queryKey: QueryKey }
}

export type ListDigestsQueryResult = NonNullable<Awaited<ReturnType<typeof listDigests>>>
export type ListDigestsQueryError = ErrorType<unknown>


/**
 * @summary List all children's book digests
 */

export function useListDigests<TData = Awaited<ReturnType<typeof listDigests>>, TError = ErrorType<unknown>>(
 params?: ListDigestsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDigests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListDigestsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateDigestUrl = () => {




  return `/api/reader`
}

/**
 * @summary Create a new daily digest
 */
export const createDigest = async (digestInput: DigestInput, options?: RequestInit): Promise<Digest> => {

  return customFetch<Digest>(getCreateDigestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      digestInput,)
  }
);}




export const getCreateDigestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDigest>>, TError,{data: BodyType<DigestInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDigest>>, TError,{data: BodyType<DigestInput>}, TContext> => {

const mutationKey = ['createDigest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDigest>>, {data: BodyType<DigestInput>}> = (props) => {
          const {data} = props ?? {};

          return  createDigest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDigestMutationResult = NonNullable<Awaited<ReturnType<typeof createDigest>>>
    export type CreateDigestMutationBody = BodyType<DigestInput>
    export type CreateDigestMutationError = ErrorType<unknown>

    /**
 * @summary Create a new daily digest
 */
export const useCreateDigest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDigest>>, TError,{data: BodyType<DigestInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createDigest>>,
        TError,
        {data: BodyType<DigestInput>},
        TContext
      > => {
      return useMutation(getCreateDigestMutationOptions(options));
    }

export const getGetDigestUrl = (id: number,) => {




  return `/api/reader/${id}`
}

/**
 * @summary Get a single digest
 */
export const getDigest = async (id: number, options?: RequestInit): Promise<Digest> => {

  return customFetch<Digest>(getGetDigestUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDigestQueryKey = (id: number,) => {
    return [
    `/api/reader/${id}`
    ] as const;
    }


export const getGetDigestQueryOptions = <TData = Awaited<ReturnType<typeof getDigest>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDigest>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDigestQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDigest>>> = ({ signal }) => getDigest(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDigest>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDigestQueryResult = NonNullable<Awaited<ReturnType<typeof getDigest>>>
export type GetDigestQueryError = ErrorType<void>


/**
 * @summary Get a single digest
 */

export function useGetDigest<TData = Awaited<ReturnType<typeof getDigest>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDigest>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDigestQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateDigestUrl = (id: number,) => {




  return `/api/reader/${id}`
}

/**
 * @summary Update a digest
 */
export const updateDigest = async (id: number,
    digestUpdate: DigestUpdate, options?: RequestInit): Promise<Digest> => {

  return customFetch<Digest>(getUpdateDigestUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      digestUpdate,)
  }
);}




export const getUpdateDigestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDigest>>, TError,{id: number;data: BodyType<DigestUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDigest>>, TError,{id: number;data: BodyType<DigestUpdate>}, TContext> => {

const mutationKey = ['updateDigest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDigest>>, {id: number;data: BodyType<DigestUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDigest(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDigestMutationResult = NonNullable<Awaited<ReturnType<typeof updateDigest>>>
    export type UpdateDigestMutationBody = BodyType<DigestUpdate>
    export type UpdateDigestMutationError = ErrorType<unknown>

    /**
 * @summary Update a digest
 */
export const useUpdateDigest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDigest>>, TError,{id: number;data: BodyType<DigestUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateDigest>>,
        TError,
        {id: number;data: BodyType<DigestUpdate>},
        TContext
      > => {
      return useMutation(getUpdateDigestMutationOptions(options));
    }

export const getDeleteDigestUrl = (id: number,) => {




  return `/api/reader/${id}`
}

/**
 * @summary Delete a digest
 */
export const deleteDigest = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteDigestUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteDigestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDigest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDigest>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteDigest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDigest>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteDigest(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDigestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDigest>>>

    export type DeleteDigestMutationError = ErrorType<unknown>

    /**
 * @summary Delete a digest
 */
export const useDeleteDigest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDigest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteDigest>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteDigestMutationOptions(options));
    }

export const getSubmitContactUrl = () => {




  return `/api/contact`
}

/**
 * @summary Submit a contact form message
 */
export const submitContact = async (contactInput: ContactInput, options?: RequestInit): Promise<ContactSubmission> => {

  return customFetch<ContactSubmission>(getSubmitContactUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactInput,)
  }
);}




export const getSubmitContactMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitContact>>, TError,{data: BodyType<ContactInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitContact>>, TError,{data: BodyType<ContactInput>}, TContext> => {

const mutationKey = ['submitContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitContact>>, {data: BodyType<ContactInput>}> = (props) => {
          const {data} = props ?? {};

          return  submitContact(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitContactMutationResult = NonNullable<Awaited<ReturnType<typeof submitContact>>>
    export type SubmitContactMutationBody = BodyType<ContactInput>
    export type SubmitContactMutationError = ErrorType<unknown>

    /**
 * @summary Submit a contact form message
 */
export const useSubmitContact = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitContact>>, TError,{data: BodyType<ContactInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof submitContact>>,
        TError,
        {data: BodyType<ContactInput>},
        TContext
      > => {
      return useMutation(getSubmitContactMutationOptions(options));
    }

export const getCreateCheckoutSessionUrl = () => {




  return `/api/checkout/create-session`
}

/**
 * @summary Create a Stripe checkout session for a book purchase
 */
export const createCheckoutSession = async (checkoutSessionInput: CheckoutSessionInput, options?: RequestInit): Promise<CheckoutSession> => {

  return customFetch<CheckoutSession>(getCreateCheckoutSessionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      checkoutSessionInput,)
  }
);}




export const getCreateCheckoutSessionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSession>>, TError,{data: BodyType<CheckoutSessionInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSession>>, TError,{data: BodyType<CheckoutSessionInput>}, TContext> => {

const mutationKey = ['createCheckoutSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckoutSession>>, {data: BodyType<CheckoutSessionInput>}> = (props) => {
          const {data} = props ?? {};

          return  createCheckoutSession(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckoutSession>>>
    export type CreateCheckoutSessionMutationBody = BodyType<CheckoutSessionInput>
    export type CreateCheckoutSessionMutationError = ErrorType<unknown>

    /**
 * @summary Create a Stripe checkout session for a book purchase
 */
export const useCreateCheckoutSession = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSession>>, TError,{data: BodyType<CheckoutSessionInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCheckoutSession>>,
        TError,
        {data: BodyType<CheckoutSessionInput>},
        TContext
      > => {
      return useMutation(getCreateCheckoutSessionMutationOptions(options));
    }

export const getGetStripePublishableKeyUrl = () => {




  return `/api/checkout/stripe-key`
}

/**
 * @summary Get Stripe publishable key for frontend
 */
export const getStripePublishableKey = async ( options?: RequestInit): Promise<StripeKey> => {

  return customFetch<StripeKey>(getGetStripePublishableKeyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStripePublishableKeyQueryKey = () => {
    return [
    `/api/checkout/stripe-key`
    ] as const;
    }


export const getGetStripePublishableKeyQueryOptions = <TData = Awaited<ReturnType<typeof getStripePublishableKey>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStripePublishableKey>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStripePublishableKeyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStripePublishableKey>>> = ({ signal }) => getStripePublishableKey({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStripePublishableKey>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStripePublishableKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getStripePublishableKey>>>
export type GetStripePublishableKeyQueryError = ErrorType<unknown>


/**
 * @summary Get Stripe publishable key for frontend
 */

export function useGetStripePublishableKey<TData = Awaited<ReturnType<typeof getStripePublishableKey>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStripePublishableKey>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStripePublishableKeyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDownloadLinkUrl = (params: GetDownloadLinkParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/checkout/download?${stringifiedParams}` : `/api/checkout/download`
}

/**
 * @summary Get a timed download token for a completed purchase
 */
export const getDownloadLink = async (params: GetDownloadLinkParams, options?: RequestInit): Promise<DownloadLink> => {

  return customFetch<DownloadLink>(getGetDownloadLinkUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDownloadLinkQueryKey = (params?: GetDownloadLinkParams,) => {
    return [
    `/api/checkout/download`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDownloadLinkQueryOptions = <TData = Awaited<ReturnType<typeof getDownloadLink>>, TError = ErrorType<void>>(params: GetDownloadLinkParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDownloadLink>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDownloadLinkQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDownloadLink>>> = ({ signal }) => getDownloadLink(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDownloadLink>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDownloadLinkQueryResult = NonNullable<Awaited<ReturnType<typeof getDownloadLink>>>
export type GetDownloadLinkQueryError = ErrorType<void>


/**
 * @summary Get a timed download token for a completed purchase
 */

export function useGetDownloadLink<TData = Awaited<ReturnType<typeof getDownloadLink>>, TError = ErrorType<void>>(
 params: GetDownloadLinkParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDownloadLink>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDownloadLinkQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getDownloadFileUrl = (params: DownloadFileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/checkout/file?${stringifiedParams}` : `/api/checkout/file`
}

/**
 * @summary Stream the purchased book file (requires valid token)
 */
export const downloadFile = async (params: DownloadFileParams, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDownloadFileUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadFileQueryKey = (params?: DownloadFileParams,) => {
    return [
    `/api/checkout/file`, ...(params ? [params] : [])
    ] as const;
    }


export const getDownloadFileQueryOptions = <TData = Awaited<ReturnType<typeof downloadFile>>, TError = ErrorType<void>>(params: DownloadFileParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadFileQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({ signal }) => downloadFile(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadFileQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFile>>>
export type DownloadFileQueryError = ErrorType<void>


/**
 * @summary Stream the purchased book file (requires valid token)
 */

export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = ErrorType<void>>(
 params: DownloadFileParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDownloadFileQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getSubscribeNewsletterUrl = () => {




  return `/api/newsletter/subscribe`
}

/**
 * @summary Subscribe an email address to the newsletter
 */
export const subscribeNewsletter = async (newsletterInput: NewsletterInput, options?: RequestInit): Promise<NewsletterSubscriber> => {

  return customFetch<NewsletterSubscriber>(getSubscribeNewsletterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newsletterInput,)
  }
);}




export const getSubscribeNewsletterMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeNewsletter>>, TError,{data: BodyType<NewsletterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeNewsletter>>, TError,{data: BodyType<NewsletterInput>}, TContext> => {

const mutationKey = ['subscribeNewsletter'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeNewsletter>>, {data: BodyType<NewsletterInput>}> = (props) => {
          const {data} = props ?? {};

          return  subscribeNewsletter(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeNewsletterMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeNewsletter>>>
    export type SubscribeNewsletterMutationBody = BodyType<NewsletterInput>
    export type SubscribeNewsletterMutationError = ErrorType<void>

    /**
 * @summary Subscribe an email address to the newsletter
 */
export const useSubscribeNewsletter = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeNewsletter>>, TError,{data: BodyType<NewsletterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof subscribeNewsletter>>,
        TError,
        {data: BodyType<NewsletterInput>},
        TContext
      > => {
      return useMutation(getSubscribeNewsletterMutationOptions(options));
    }

